#!/usr/bin/env python3
"""
viewer.py
- Reads path.json generated by C++ and creates viewer/map.html (folium)
- pip install folium
"""
import folium, json, os, webbrowser
from folium.plugins import BeautifyIcon

PJ = "path.json"
OUT = "viewer/map.html"
if not os.path.exists(PJ):
    print("Run safepath_core to generate path.json first.")
    raise SystemExit(1)
j = json.load(open(PJ))
routes = j.get("routes", [])

# center on first point
if len(routes)==0:
    print("No routes in path.json")
    raise SystemExit(1)

first = routes[0]
center = (first['points'][0]['lat'], first['points'][0]['lon'])
m = folium.Map(location=center, zoom_start=13, tiles='OpenStreetMap')

colors = ['red','darkorange','gold','blue','green']
for i,rt in enumerate(routes):
    coords = [(p['lat'], p['lon']) for p in rt['points']]
    folium.PolyLine(coords, color=colors[i%len(colors)], weight=6 if i==0 else 4, opacity=0.9).add_to(m)
    # markers
    folium.Marker(coords[0], popup="Start: "+rt['points'][0]['name'], icon=BeautifyIcon(text='S', background_color=colors[i%len(colors)])).add_to(m)
    folium.Marker(coords[-1], popup="End: "+rt['points'][-1]['name'], icon=BeautifyIcon(text='D', background_color=colors[i%len(colors)])).add_to(m)

# add info pane as html
info_html = "<h4>Routes summary</h4>"
for i,rt in enumerate(routes):
    info_html += f"<b>{'Best' if i==0 else 'Alt ' + str(i)}</b>: {rt['distance_m']/1000:.2f} km, ETA {rt['duration_min']} min<br>"
m.get_root().html.add_child(folium.Element(f"<div style='position: fixed; top: 10px; right: 10px; z-index:9999; background:white; padding:10px;'>{info_html}</div>"))

os.makedirs("viewer", exist_ok=True)
m.save(OUT)
print("Saved", OUT)
webbrowser.open("file://" + os.path.abspath(OUT))
